/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Seo = {
    _type: 'seo';
    title?: string;
    description?: string;
    shareImage?: Figure;
    hideFromSearch?: boolean;
};

export type RichText = Array<{
    children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
}>;

export type Link = {
    _type: 'link';
    label?: string;
    href?: string;
};

export type SanityImageAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Figure = {
    _type: 'figure';
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
};

export type Award = {
    _type: 'award';
    year?: string;
    organization?: string;
    title?: string;
    category?: string;
};

export type SiteSettings = {
    _id: string;
    _type: 'siteSettings';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    siteName?: string;
    navLinks?: Array<
        {
            _key: string;
        } & Link
    >;
    navCta?: Link;
    email?: string;
    phone?: string;
    socialLinks?: Array<
        {
            _key: string;
        } & Link
    >;
    footerHeadline?: string;
    form?: {
        nameLabel?: string;
        emailLabel?: string;
        messageLabel?: string;
        submitLabel?: string;
    };
    defaultSeo?: Seo;
};

export type Testimonial = {
    _id: string;
    _type: 'testimonial';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    quote?: string;
    name?: string;
    role?: string;
};

export type Service = {
    _id: string;
    _type: 'service';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    image?: Figure;
};

export type Discipline = {
    _id: string;
    _type: 'discipline';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
};

export type DisciplineReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'discipline';
};

export type CaseStudy = {
    _id: string;
    _type: 'caseStudy';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    disciplines?: Array<
        {
            _key: string;
        } & DisciplineReference
    >;
    description?: RichText;
    recognitionLabel?: string;
    recognition?: Array<string>;
    thumbnail?: Figure;
    images?: Array<
        {
            _key: string;
        } & Figure
    >;
    seo?: Seo;
};

export type Slug = {
    _type: 'slug';
    current?: string;
    source?: string;
};

export type ContactPage = {
    _id: string;
    _type: 'contactPage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo?: Seo;
};

export type CaseStudyReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'caseStudy';
};

export type WorkPage = {
    _id: string;
    _type: 'workPage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    heading?: string;
    projects?: Array<
        {
            _key: string;
        } & CaseStudyReference
    >;
    seo?: Seo;
};

export type AboutPage = {
    _id: string;
    _type: 'aboutPage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    introLabel?: string;
    intro?: string;
    valuesLabel?: string;
    values?: Array<{
        body?: RichText;
        _type: 'valueColumn';
        _key: string;
    }>;
    contactLabel?: string;
    seo?: Seo;
};

export type TestimonialReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'testimonial';
};

export type ServiceReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'service';
};

export type HomePage = {
    _id: string;
    _type: 'homePage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    heroImage?: Figure;
    approachLabel?: string;
    approachStatement?: string;
    approachImage?: Figure;
    approachBody?: string;
    approachCta?: Link;
    awardsLabel?: string;
    awards?: Array<
        {
            _key: string;
        } & Award
    >;
    testimonials?: Array<
        {
            _key: string;
        } & TestimonialReference
    >;
    galleryImages?: Array<
        {
            _key: string;
        } & Figure
    >;
    servicesLabel?: string;
    services?: Array<
        {
            _key: string;
        } & ServiceReference
    >;
    projectsLabel?: string;
    featuredProjects?: Array<
        {
            _key: string;
        } & CaseStudyReference
    >;
    seo?: Seo;
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | Seo
    | RichText
    | Link
    | SanityImageAssetReference
    | Figure
    | Award
    | SiteSettings
    | Testimonial
    | Service
    | Discipline
    | DisciplineReference
    | CaseStudy
    | Slug
    | ContactPage
    | CaseStudyReference
    | WorkPage
    | AboutPage
    | TestimonialReference
    | ServiceReference
    | HomePage
    | SanityImageCrop
    | SanityImageHotspot
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    siteName,    navLinks[]{ _key, label, href },    navCta { label, href },    email,    phone,    socialLinks[]{ _key, label, href },    footerHeadline,    form,    defaultSeo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type SITE_SETTINGS_QUERY_RESULT =
    | {
          siteName: null;
          navLinks: null;
          navCta: null;
          email: null;
          phone: null;
          socialLinks: null;
          footerHeadline: null;
          form: null;
          defaultSeo: null;
      }
    | {
          siteName: string | null;
          navLinks: Array<{
              _key: string;
              label: string | null;
              href: string | null;
          }> | null;
          navCta: {
              label: string | null;
              href: string | null;
          } | null;
          email: string | null;
          phone: string | null;
          socialLinks: Array<{
              _key: string;
              label: string | null;
              href: string | null;
          }> | null;
          footerHeadline: string | null;
          form: {
              nameLabel?: string;
              emailLabel?: string;
              messageLabel?: string;
              submitLabel?: string;
          } | null;
          defaultSeo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | null;

// Source: src/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    heroImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    approachLabel,    approachStatement,    approachImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    approachBody,    approachCta { label, href },    awardsLabel,    awards[]{ _key, year, organization, title, category },    testimonials[]->{ _id, quote, name, role },    galleryImages[] {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    servicesLabel,    services[]->{ _id, title, description, image {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }} },    projectsLabel,    featuredProjects[]-> {    _id,    title,    "slug": slug.current,    thumbnail {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    "disciplines": disciplines[]->title},    seo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type HOME_PAGE_QUERY_RESULT =
    | {
          heroImage: null;
          approachLabel: null;
          approachStatement: null;
          approachImage: null;
          approachBody: null;
          approachCta: null;
          awardsLabel: null;
          awards: null;
          testimonials: null;
          galleryImages: null;
          servicesLabel: null;
          services: null;
          projectsLabel: null;
          featuredProjects: null;
          seo: null;
      }
    | {
          heroImage: null;
          approachLabel: null;
          approachStatement: null;
          approachImage: null;
          approachBody: null;
          approachCta: null;
          awardsLabel: null;
          awards: null;
          testimonials: null;
          galleryImages: null;
          servicesLabel: null;
          services: null;
          projectsLabel: null;
          featuredProjects: null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | {
          heroImage: {
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              asset: {
                  _id: string;
                  url: string | null;
                  metadata: {
                      lqip: string | null;
                      dimensions: {
                          width: number | null;
                          height: number | null;
                          aspectRatio: number | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
          approachLabel: string | null;
          approachStatement: string | null;
          approachImage: {
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              asset: {
                  _id: string;
                  url: string | null;
                  metadata: {
                      lqip: string | null;
                      dimensions: {
                          width: number | null;
                          height: number | null;
                          aspectRatio: number | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
          approachBody: string | null;
          approachCta: {
              label: string | null;
              href: string | null;
          } | null;
          awardsLabel: string | null;
          awards: Array<{
              _key: string;
              year: string | null;
              organization: string | null;
              title: string | null;
              category: string | null;
          }> | null;
          testimonials: Array<{
              _id: string;
              quote: string | null;
              name: string | null;
              role: string | null;
          }> | null;
          galleryImages: Array<{
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              asset: {
                  _id: string;
                  url: string | null;
                  metadata: {
                      lqip: string | null;
                      dimensions: {
                          width: number | null;
                          height: number | null;
                          aspectRatio: number | null;
                      } | null;
                  } | null;
              } | null;
          }> | null;
          servicesLabel: string | null;
          services: Array<{
              _id: string;
              title: string | null;
              description: string | null;
              image: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          }> | null;
          projectsLabel: string | null;
          featuredProjects: Array<{
              _id: string;
              title: string | null;
              slug: string | null;
              thumbnail: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
              disciplines: Array<string | null> | null;
          }> | null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | null;

// Source: src/lib/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    introLabel,    intro,    valuesLabel,    values[]{ _key, body },    contactLabel,    seo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type ABOUT_PAGE_QUERY_RESULT =
    | {
          introLabel: null;
          intro: null;
          valuesLabel: null;
          values: null;
          contactLabel: null;
          seo: null;
      }
    | {
          introLabel: null;
          intro: null;
          valuesLabel: null;
          values: null;
          contactLabel: null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | {
          introLabel: string | null;
          intro: string | null;
          valuesLabel: string | null;
          values: Array<{
              _key: string;
              body: RichText | null;
          }> | null;
          contactLabel: string | null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | null;

// Source: src/lib/sanity/queries.ts
// Variable: WORK_PAGE_QUERY
// Query: *[_id == "workPage"][0]{    heading,    projects[]-> {    _id,    title,    "slug": slug.current,    thumbnail {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    "disciplines": disciplines[]->title},    seo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type WORK_PAGE_QUERY_RESULT =
    | {
          heading: null;
          projects: null;
          seo: null;
      }
    | {
          heading: null;
          projects: null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | {
          heading: string | null;
          projects: Array<{
              _id: string;
              title: string | null;
              slug: string | null;
              thumbnail: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
              disciplines: Array<string | null> | null;
          }> | null;
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | null;

// Source: src/lib/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    seo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type CONTACT_PAGE_QUERY_RESULT =
    | {
          seo: null;
      }
    | {
          seo: {
              title: string | null;
              description: string | null;
              hideFromSearch: boolean | null;
              shareImage: {
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
                  asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                          lqip: string | null;
                          dimensions: {
                              width: number | null;
                              height: number | null;
                              aspectRatio: number | null;
                          } | null;
                      } | null;
                  } | null;
              } | null;
          } | null;
      }
    | null;

// Source: src/lib/sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current }
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
    slug: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    "disciplines": disciplines[]->title,    description,    recognitionLabel,    recognition,    thumbnail {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    images[] {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }},    seo {    title,    description,    hideFromSearch,    shareImage {    alt,    hotspot,    crop,    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }}}}
export type CASE_STUDY_QUERY_RESULT = {
    _id: string;
    title: string | null;
    slug: string | null;
    disciplines: Array<string | null> | null;
    description: RichText | null;
    recognitionLabel: string | null;
    recognition: Array<string> | null;
    thumbnail: {
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
            _id: string;
            url: string | null;
            metadata: {
                lqip: string | null;
                dimensions: {
                    width: number | null;
                    height: number | null;
                    aspectRatio: number | null;
                } | null;
            } | null;
        } | null;
    } | null;
    images: Array<{
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
            _id: string;
            url: string | null;
            metadata: {
                lqip: string | null;
                dimensions: {
                    width: number | null;
                    height: number | null;
                    aspectRatio: number | null;
                } | null;
            } | null;
        } | null;
    }> | null;
    seo: {
        title: string | null;
        description: string | null;
        hideFromSearch: boolean | null;
        shareImage: {
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
                _id: string;
                url: string | null;
                metadata: {
                    lqip: string | null;
                    dimensions: {
                        width: number | null;
                        height: number | null;
                        aspectRatio: number | null;
                    } | null;
                } | null;
            } | null;
        } | null;
    } | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
    interface SanityQueries {
        '*[_id == "siteSettings"][0]{\n    siteName,\n    navLinks[]{ _key, label, href },\n    navCta { label, href },\n    email,\n    phone,\n    socialLinks[]{ _key, label, href },\n    footerHeadline,\n    form,\n    defaultSeo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': SITE_SETTINGS_QUERY_RESULT;
        '*[_id == "homePage"][0]{\n    heroImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n\n    approachLabel,\n    approachStatement,\n    approachImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n    approachBody,\n    approachCta { label, href },\n\n    awardsLabel,\n    awards[]{ _key, year, organization, title, category },\n\n    testimonials[]->{ _id, quote, name, role },\n\n    galleryImages[] {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n\n    servicesLabel,\n    services[]->{ _id, title, description, image {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n} },\n\n    projectsLabel,\n    featuredProjects[]-> {\n    _id,\n    title,\n    "slug": slug.current,\n    thumbnail {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n    "disciplines": disciplines[]->title\n},\n\n    seo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': HOME_PAGE_QUERY_RESULT;
        '*[_id == "aboutPage"][0]{\n    introLabel,\n    intro,\n    valuesLabel,\n    values[]{ _key, body },\n    contactLabel,\n    seo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': ABOUT_PAGE_QUERY_RESULT;
        '*[_id == "workPage"][0]{\n    heading,\n    projects[]-> {\n    _id,\n    title,\n    "slug": slug.current,\n    thumbnail {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n    "disciplines": disciplines[]->title\n},\n    seo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': WORK_PAGE_QUERY_RESULT;
        '*[_id == "contactPage"][0]{\n    seo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': CONTACT_PAGE_QUERY_RESULT;
        '*[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current }': CASE_STUDY_SLUGS_QUERY_RESULT;
        '*[_type == "caseStudy" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    "disciplines": disciplines[]->title,\n    description,\n    recognitionLabel,\n    recognition,\n    thumbnail {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n    images[] {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n},\n    seo {\n    title,\n    description,\n    hideFromSearch,\n    shareImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{ _id, url, metadata { lqip, dimensions { width, height, aspectRatio } } }\n}\n}\n}': CASE_STUDY_QUERY_RESULT;
    }
}
